config/routes.rb
Myapp::Application.routes.draw do
  resources :much_withdraws

  resources :very_buildings

  resources :very_loots

  resources :tests

  get "home/index"

  get '/such_command_center/wow_visit/:id', to: 'such_command_center#wow_visit', as: 'wow_visit'

root to: 'such_command_center#index'

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/much_withdraw.rb
class MuchWithdraw < ActiveRecord::Base
end

app/controllers/much_withdraws_controller.rb
class MuchWithdrawsController < ApplicationController
  before_action :set_much_withdraw, only: [:show, :edit, :update, :destroy]

  # GET /much_withdraws
  # GET /much_withdraws.json
  def index
    @much_withdraws = MuchWithdraw.all
  end

  # GET /much_withdraws/1
  # GET /much_withdraws/1.json
  def show
  end

  # GET /much_withdraws/new
  def new
    @much_withdraw = MuchWithdraw.new
  end

  # GET /much_withdraws/1/edit
  def edit
  end

  # POST /much_withdraws
  # POST /much_withdraws.json
  def create
    @much_withdraw = MuchWithdraw.new
    @much_withdraw.building_id = params[:building_id]
    @much_withdraw.such_date = Time.zone.now.to_datetime
    b = VeryBuilding.find_by_id(@much_withdraw.building_id)
    if(b.such_type=="SuchGenerator")
      @much_withdraw.amount = 100
      current_user.energy+=@much_withdraw.amount
    elsif
      @much_withdraw.amount = 10
      current_user.units+=@much_withdraw.amount
      current_user.energy-=@much_withdraw.amount*10
    end

    last_withdraw=MuchWithdraw.where(:building_id=>b.id).last

    respond_to do |format|
      if last_withdraw==nil
        @much_withdraw.save
        current_user.save
        format.html { redirect_to "/", notice: 'much withdraw so success' }
      elsif last_withdraw.such_date + 2*60*60 - Time.zone.now.to_datetime > 0
        format.html { redirect_to "/", notice: 'pls wait.' }
        format.json { render json: @very_loot.errors, status: :unprocessable_entity }
      elsif @much_withdraw.save
        current_user.save
        format.html { redirect_to "/", notice: 'much withdraw so success' }
        format.json { render action: 'show', status: :created, location: @much_withdraw }
      else
        format.html { redirect_to "/", notice: 'so error many sad'+(last_withdraw.such_date + 2*60*60 - Time.zone.now.to_datetime).to_s }
      end
    end
  end

  # PATCH/PUT /much_withdraws/1
  # PATCH/PUT /much_withdraws/1.json
  def update
    respond_to do |format|
      if @much_withdraw.update(much_withdraw_params)
        format.html { redirect_to "/", notice: 'much withdraw so success' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @much_withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /much_withdraws/1
  # DELETE /much_withdraws/1.json
  def destroy
    @much_withdraw.destroy
    respond_to do |format|
      format.html { redirect_to much_withdraws_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_much_withdraw
      @much_withdraw = MuchWithdraw.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def much_withdraw_params
      params.require(:much_withdraw).permit(:building_id, :such_date, :amount)
    end
end

app/helpers/much_withdraws_helper.rb
module MuchWithdrawsHelper
end

app/views/much_withdraws/_form.html.erb
<%= form_for(@much_withdraw) do |f| %>
  <% if @much_withdraw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@much_withdraw.errors.count, "error") %> prohibited this much_withdraw from being saved:</h2>

      <ul>
      <% @much_withdraw.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.number_field :building_id %>
  </div>
  <div class="field">
    <%= f.label :such_date %><br>
    <%= f.datetime_select :such_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/much_withdraws/edit.html.erb
<h1>Editing much_withdraw</h1>

<%= render 'form' %>

<%= link_to 'Show', @much_withdraw %> |
<%= link_to 'Back', much_withdraws_path %>

app/views/much_withdraws/index.html.erb
<h1>Listing much_withdraws</h1>

<table>
  <thead>
    <tr>
      <th>Building</th>
      <th>Such date</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @much_withdraws.each do |much_withdraw| %>
      <tr>
        <td><%= much_withdraw.building_id %></td>
        <td><%= much_withdraw.such_date %></td>
        <td><%= much_withdraw.amount %></td>
        <td><%= link_to 'Show', much_withdraw %></td>
        <td><%= link_to 'Edit', edit_much_withdraw_path(much_withdraw) %></td>
        <td><%= link_to 'Destroy', much_withdraw, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Much withdraw', new_much_withdraw_path %>

app/views/much_withdraws/new.html.erb
<h1>New much_withdraw</h1>

<%= render 'form' %>

<%= link_to 'Back', much_withdraws_path %>

app/views/much_withdraws/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building:</strong>
  <%= @much_withdraw.building_id %>
</p>

<p>
  <strong>Such date:</strong>
  <%= @much_withdraw.such_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @much_withdraw.amount %>
</p>

<%= link_to 'Edit', edit_much_withdraw_path(@much_withdraw) %> |
<%= link_to 'Back', much_withdraws_path %>