config/routes.rb
Myapp::Application.routes.draw do
  resources :much_withdraws

  resources :very_buildings

  resources :very_loots

  resources :tests

  get "home/index"

  get '/such_command_center/wow_visit/:id', to: 'such_command_center#wow_visit', as: 'wow_visit'

root to: 'such_command_center#index'

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/very_building.rb
class VeryBuilding < ActiveRecord::Base
end

app/controllers/very_buildings_controller.rb
class VeryBuildingsController < ApplicationController
  before_action :set_very_building, only: [:show, :edit, :update, :destroy]

  # GET /very_buildings
  # GET /very_buildings.json
  def index
    @very_buildings = VeryBuilding.all
  end

  # GET /very_buildings/1
  # GET /very_buildings/1.json
  def show
  end

  # GET /very_buildings/new
  def new
    @very_building = VeryBuilding.new
  end

  # GET /very_buildings/1/edit
  def edit
  end

  # POST /very_buildings
  # POST /very_buildings.json
  def create
#    @very_building = VeryBuilding.new(very_building_params)
    @very_building = VeryBuilding.new
    @very_building.user_id = current_user.id
    @very_building.such_type = params[:such_type]
    @very_building.hp = 100
    @very_building.position = params[:position].to_i

    respond_to do |format|
      if current_user.energy <1000
        format.html { redirect_to "/", notice: 'such error.' }
        format.json { render json: @very_building.errors, status: :unprocessable_entity }
      elsif @very_building.save
        current_user.energy-=1000
        current_user.save
        format.html { redirect_to "/", notice: 'Very building was successfully created.' }
        format.json { render action: 'show', status: :created, location: @very_building }
      else
        format.html { redirect_to "/", notice: 'such error.' }
        format.json { render json: @very_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /very_buildings/1
  # PATCH/PUT /very_buildings/1.json
  def update
    respond_to do |format|
      if @very_building.update(very_building_params)
        format.html { redirect_to @very_building, notice: 'Very building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @very_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /very_buildings/1
  # DELETE /very_buildings/1.json
  def destroy
    @very_building.destroy
    respond_to do |format|
      format.html { redirect_to very_buildings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_very_building
      @very_building = VeryBuilding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def very_building_params
      params.require(:very_building).permit(:user_id, :such_type, :position, :hp)
    end
end

app/helpers/very_buildings_helper.rb
module VeryBuildingsHelper
end

app/views/very_buildings/_form.html.erb
<%= form_for(@very_building) do |f| %>
  <% if @very_building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@very_building.errors.count, "error") %> prohibited this very_building from being saved:</h2>

      <ul>
      <% @very_building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :such_type %><br>
    <%= f.text_field :such_type %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :hp %><br>
    <%= f.number_field :hp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/very_buildings/edit.html.erb
<h1>Editing very_building</h1>

<%= render 'form' %>

<%= link_to 'Show', @very_building %> |
<%= link_to 'Back', very_buildings_path %>

app/views/very_buildings/index.html.erb
<h1>Listing very_buildings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Such type</th>
      <th>Position</th>
      <th>Hp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @very_buildings.each do |very_building| %>
      <tr>
        <td><%= very_building.user_id %></td>
        <td><%= very_building.such_type %></td>
        <td><%= very_building.position %></td>
        <td><%= very_building.hp %></td>
        <td><%= link_to 'Show', very_building %></td>
        <td><%= link_to 'Edit', edit_very_building_path(very_building) %></td>
        <td><%= link_to 'Destroy', very_building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Very building', new_very_building_path %>

app/views/very_buildings/new.html.erb
<h1>New very_building</h1>

<%= render 'form' %>

<%= link_to 'Back', very_buildings_path %>

app/views/very_buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @very_building.user_id %>
</p>

<p>
  <strong>Such type:</strong>
  <%= @very_building.such_type %>
</p>

<p>
  <strong>Position:</strong>
  <%= @very_building.position %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @very_building.hp %>
</p>

<%= link_to 'Edit', edit_very_building_path(@very_building) %> |
<%= link_to 'Back', very_buildings_path %>