config/routes.rb
Myapp::Application.routes.draw do
  resources :much_withdraws

  resources :very_buildings

  resources :very_loots

  resources :tests

  get "home/index"

  get '/such_command_center/wow_visit/:id', to: 'such_command_center#wow_visit', as: 'wow_visit'

root to: 'such_command_center#index'

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/very_loot.rb
class VeryLoot < ActiveRecord::Base
end

app/controllers/very_loots_controller.rb
class VeryLootsController < ApplicationController
  before_action :set_very_loot, only: [:show, :edit, :update, :destroy]

  # GET /very_loots
  # GET /very_loots.json
  def index
    @very_loots = VeryLoot.all
  end

  # GET /very_loots/1
  # GET /very_loots/1.json
  def show
  end

  # GET /very_loots/new
  def new
    @very_loot = VeryLoot.new
  end

  # GET /very_loots/1/edit
  def edit
  end

  # POST /very_loots
  # POST /very_loots.json
  def create
    @very_loot = VeryLoot.new

    @very_loot.such_date = Time.zone.now.to_datetime
    @very_loot.user_id = current_user.id
    @very_loot.amount = 200
    u=User.find_by_id(current_user.id)
    u.energy+=200

    respond_to do |format|
      if VeryLoot.where(:user_id => current_user.id).last==nil
        @very_loot.save
        u.save
        format.html { redirect_to "/", notice: 'Very loot was successfully created.' }
      elsif VeryLoot.where(:user_id => current_user.id).last.such_date + 2*60*60 - Time.zone.now.to_datetime > 0
        format.html { redirect_to "/", notice: 'pls wait.' }
        format.json { render json: @very_loot.errors, status: :unprocessable_entity }
      elsif @very_loot.save
        u.save
        format.html { redirect_to "/", notice: 'very loot' }
      else
        format.html { render action: 'new' }
        format.json { render json: @very_loot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /very_loots/1
  # PATCH/PUT /very_loots/1.json
  def update
    respond_to do |format|
      if @very_loot.update(very_loot_params)
        format.html { redirect_to @very_loot, notice: 'Very loot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @very_loot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /very_loots/1
  # DELETE /very_loots/1.json
  def destroy
    @very_loot.destroy
    respond_to do |format|
      format.html { redirect_to very_loots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_very_loot
      @very_loot = VeryLoot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def very_loot_params
      params.require(:very_loot).permit(:user_id, :amount, :such_date)
    end
end

app/helpers/very_loots_helper.rb
module VeryLootsHelper
end

app/views/very_loots/_form.html.erb
<%= form_for(@very_loot) do |f| %>
  <% if @very_loot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@very_loot.errors.count, "error") %> prohibited this very_loot from being saved:</h2>

      <ul>
      <% @very_loot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :such_date %><br>
    <%= f.datetime_select :such_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/very_loots/edit.html.erb
<h1>Editing very_loot</h1>

<%= render 'form' %>

<%= link_to 'Show', @very_loot %> |
<%= link_to 'Back', very_loots_path %>

app/views/very_loots/index.html.erb
<h1>Listing very_loots</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Amount</th>
      <th>Such date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @very_loots.each do |very_loot| %>
      <tr>
        <td><%= very_loot.user_id %></td>
        <td><%= very_loot.amount %></td>
        <td><%= very_loot.such_date %></td>
        <td><%= link_to 'Show', very_loot %></td>
        <td><%= link_to 'Edit', edit_very_loot_path(very_loot) %></td>
        <td><%= link_to 'Destroy', very_loot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Very loot', new_very_loot_path %>

app/views/very_loots/new.html.erb
<h1>New very_loot</h1>

<%= render 'form' %>

<%= link_to 'Back', very_loots_path %>

app/views/very_loots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @very_loot.user_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @very_loot.amount %>
</p>

<p>
  <strong>Such date:</strong>
  <%= @very_loot.such_date %>
</p>

<%= link_to 'Edit', edit_very_loot_path(@very_loot) %> |
<%= link_to 'Back', very_loots_path %>